sudo: required
services:
    - docker

before_install:
    - docker build -t balaji/docker-react1 -f Dockerfile.dev .

script:
    - docker run balaji/docker-react1 npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dockernew"
    env: "Dockernew-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-304552109372"
    bucket_path: "dockernew"
    edge: true
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        

